// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnfqakbiobwitqkkdxpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFuZnFha2Jpb2J3aXRxa2tkeHBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNDQyMDUsImV4cCI6MjA2NTcyMDIwNX0.gwKNWn3zqlFBvYt6vCJXMUtsLWfRqC-6aCj9HjYA2f4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);